// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// make_covlist
arma::field<arma::mat> make_covlist(const arma::mat& coords, int nsim);
RcppExport SEXP _fbttbchol_make_covlist(SEXP coordsSEXP, SEXP nsimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    rcpp_result_gen = Rcpp::wrap(make_covlist(coords, nsim));
    return rcpp_result_gen;
END_RCPP
}
// arma_chol
arma::mat arma_chol(const arma::mat& x);
RcppExport SEXP _fbttbchol_arma_chol(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_chol(x));
    return rcpp_result_gen;
END_RCPP
}
// arma_invchol
arma::mat arma_invchol(const arma::mat& x);
RcppExport SEXP _fbttbchol_arma_invchol(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_invchol(x));
    return rcpp_result_gen;
END_RCPP
}
// arma_invchol_list
arma::field<arma::mat> arma_invchol_list(const arma::mat& coords, const arma::field<arma::mat>& covlist, bool print);
RcppExport SEXP _fbttbchol_arma_invchol_list(SEXP coordsSEXP, SEXP covlistSEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type covlist(covlistSEXP);
    Rcpp::traits::input_parameter< bool >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_invchol_list(coords, covlist, print));
    return rcpp_result_gen;
END_RCPP
}
// f_chol
arma::mat f_chol(const arma::mat& C, int k, int n);
RcppExport SEXP _fbttbchol_f_chol(SEXP CSEXP, SEXP kSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(f_chol(C, k, n));
    return rcpp_result_gen;
END_RCPP
}
// f_invchol
arma::mat f_invchol(const arma::mat& C, int k, int n);
RcppExport SEXP _fbttbchol_f_invchol(SEXP CSEXP, SEXP kSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(f_invchol(C, k, n));
    return rcpp_result_gen;
END_RCPP
}
// f_invchol_list
arma::field<arma::mat> f_invchol_list(const arma::mat& coords, int k, int n, const arma::field<arma::mat>& covlist, bool print);
RcppExport SEXP _fbttbchol_f_invchol_list(SEXP coordsSEXP, SEXP kSEXP, SEXP nSEXP, SEXP covlistSEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type covlist(covlistSEXP);
    Rcpp::traits::input_parameter< bool >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(f_invchol_list(coords, k, n, covlist, print));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fbttbchol_make_covlist", (DL_FUNC) &_fbttbchol_make_covlist, 2},
    {"_fbttbchol_arma_chol", (DL_FUNC) &_fbttbchol_arma_chol, 1},
    {"_fbttbchol_arma_invchol", (DL_FUNC) &_fbttbchol_arma_invchol, 1},
    {"_fbttbchol_arma_invchol_list", (DL_FUNC) &_fbttbchol_arma_invchol_list, 3},
    {"_fbttbchol_f_chol", (DL_FUNC) &_fbttbchol_f_chol, 3},
    {"_fbttbchol_f_invchol", (DL_FUNC) &_fbttbchol_f_invchol, 3},
    {"_fbttbchol_f_invchol_list", (DL_FUNC) &_fbttbchol_f_invchol_list, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fbttbchol(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
