# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_covlist <- function(coords, nsim = 10L) {
    .Call(`_fbttbchol_make_covlist`, coords, nsim)
}

arma_chol <- function(x) {
    .Call(`_fbttbchol_arma_chol`, x)
}

arma_invchol <- function(x) {
    .Call(`_fbttbchol_arma_invchol`, x)
}

arma_invchol_list <- function(coords, covlist, print = FALSE) {
    .Call(`_fbttbchol_arma_invchol_list`, coords, covlist, print)
}

f_chol <- function(C, k, n) {
    .Call(`_fbttbchol_f_chol`, C, k, n)
}

f_invchol <- function(C, k, n) {
    .Call(`_fbttbchol_f_invchol`, C, k, n)
}

f_invchol_list <- function(coords, k, n, covlist, print = FALSE) {
    .Call(`_fbttbchol_f_invchol_list`, coords, k, n, covlist, print)
}

